/*
 * Copyright 2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Enables digital function */
#define IOCON_PIO_DIGITAL_EN 0x0100u
/*!
 * @brief Selects pin function 1 */
#define IOCON_PIO_FUNC1 0x01u
/*!
 * @brief Input function is not inverted */
#define IOCON_PIO_INV_DI 0x00u
/*!
 * @brief No addition pin function */
#define IOCON_PIO_MODE_INACT 0x00u
/*!
 * @brief Open drain is disabled */
#define IOCON_PIO_OPENDRAIN_DI 0x00u
/*!
 * @brief Standard mode, output slew rate control is enabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO0_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO0_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO0_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO0_22_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_11_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Disable digital mode. Digital input set to 0. */
#define PIO1_19_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_20_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_21_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_22_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_28_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_4_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Analog switch input control: Analog switch is closed. (enable) */
#define PIO1_5_ASW0_ENABLE 0x01u
/*!
 * @brief Select Digital mode: Disable digital mode. Digital input set to 0. */
#define PIO1_5_DIGIMODE_ANALOG 0x00u
/*!
 * @brief
 * Mode select (on-chip pull-up/pull-down resistor control): Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_5_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_6_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_8_DIGIMODE_DIGITAL 0x01u

/*! @name FC0_RXD_SDA_MOSI_DATA (number 93), JP78[2]/P0_29-FC0_RXD_SDA_MOSI_DATA-TRACED2
  @{ */
/* @} */

/*! @name FC0_TXD_SCL_MISO_WS (number 95), JP49[3]/JP80[2]/P0_30-FC0_TXD_SCL_MISO_WS-TRACED1-CAN0_TD
  @{ */
/* @} */

/*! @name PIO0_22 (number 78), J12[8]/JP72[2]/P0_22
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GREEN_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_GREEN_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO1_28 (number 72), J122[16]/P1_28
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_RED_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_RED_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_17 (number 41), J8[2]/P0_17
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW3_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW3_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_SW3_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW3_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW3_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO1_11 (number 94), J12[3]/P1_11-CTIMER_INP5-EXTTRIG_IN8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_BLUE_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_BLUE_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                          /* @} */

#define PIO0_29_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO0_30_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode: Enable Digital mode. Digital input is enabled. */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
